# Generated by Django 4.1 on 2022-09-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contact_options_alter_home_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='files',
            field=models.ManyToManyField(blank=True, null=True, to='core.file', verbose_name='files'),
        ),
    ]
