# Generated by Django 4.1 on 2022-09-17 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_subscription_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.FileField(help_text='only .svg and .png files can be uploaded', upload_to='icons/', validators=[django.core.validators.FileExtensionValidator(['svg', 'png'])], verbose_name='icon'),
        ),
    ]
