# Generated by Django 4.1 on 2022-09-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_lesson_level_type_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, unique=True, verbose_name='order'),
            preserve_default=False,
        ),
    ]
