# Generated by Django 4.1 on 2022-09-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_type_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='order'),
        ),
    ]
