# Generated by Django 4.1 on 2022-09-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_type_options_alter_type_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.CharField(default=1, max_length=512, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='images/', verbose_name='image'),
            preserve_default=False,
        ),
    ]
