ALLOWED_HOSTS = ['*']

HOST = '127.0.0.1:8000'
EMAIL_HOST_USER = 'EMAIL_HOST_USER'
EMAIL_HOST_PASSWORD = 'EMAIL_HOST_PASSWORD'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'POSTGRES_DB',
        'USER': 'POSTGRES_USER',
        'PASSWORD': 'POSTGRES_PASSWORD',
        'HOST': 'POSTGRES_HOST',
        'PORT': 'POSTGRES_PORT'
    }
}
